### ISSUE TITLE
error when run nf start in physical API 

### ISSUE THREAD

**Issue by boonpin1975** [lelylan/lelylan#139] opened 2016-02-25 10:10 UTC
I have up the mongod services 
 ps -efww | grep mongo
mongodb  10220     1  0 17:57 ?        00:00:02 /usr/bin/mongod --unixSocketPrefix=/var/run/mongodb --config /etc/mongodb.conf run

, and when run the nf start in physical API directory , I got this
[OKAY] Loaded ENV .env File as KEY=VALUE Format
[OKAY] Trimming display Output to 127 Columns
18:07:46 worker.1 |  /home/nemo/physicals/node_modules/mongodb/lib/mongodb/connection/server.js:437
18:07:46 worker.1 |          throw err;
18:07:46 worker.1 |  ^
18:07:46 worker.1 |  TypeError: Uncaught, unspecified "error" event.
18:07:46 worker.1 |    at TypeError (<anonymous>:null:null)
18:07:46 worker.1 |    at QueryStream.EventEmitter.emit (events.js:74:15)
18:07:46 worker.1 |    at QueryStream.destroy (/home/nemo/physicals/node_modules/mongoose/lib/querystream.js:280:10)
18:07:46 worker.1 |    at QueryStream._onNextObject (/home/nemo/physicals/node_modules/mongoose/lib/querystream.js:186:24)
18:07:46 worker.1 |    at cursorcb (/home/nemo/physicals/node_modules/mongoose/lib/querystream.js:154:10)
18:07:46 worker.1 |    at /home/nemo/physicals/node_modules/mongodb/lib/mongodb/cursor.js:504:39
18:07:46 worker.1 |    at Cursor.close (/home/nemo/physicals/node_modules/mongodb/lib/mongodb/cursor.js:776:5)
18:07:46 worker.1 |    at [object Object].commandHandler (/home/nemo/physicals/node_modules/mongodb/lib/mongodb/cursor.js:504:21)
18:07:46 worker.1 |    at [object Object].g (events.js:180:16)
18:07:46 worker.1 |    at [object Object].EventEmitter.emit (events.js:106:17)
18:07:46 worker.1 |    at Db._callHandler (/home/nemo/physicals/node_modules/mongodb/lib/mongodb/db.js:1472:25)
18:07:46 worker.1 |    at /home/nemo/physicals/node_modules/mongodb/lib/mongodb/connection/server.js:430:30
18:07:46 worker.1 |    at [object Object].MongoReply.parseBody (/home/nemo/physicals/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:127:5…
18:07:46 worker.1 |    at [object Object].<anonymous> (/home/nemo/physicals/node_modules/mongodb/lib/mongodb/connection/server.js:389:22)
18:07:46 worker.1 |    at [object Object].EventEmitter.emit (events.js:95:17)
18:07:46 worker.1 |    at [object Object].<anonymous> (/home/nemo/physicals/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:13)
18:07:46 worker.1 |    at [object Object].EventEmitter.emit (events.js:98:17)
18:07:46 worker.1 |    at Socket.<anonymous> (/home/nemo/physicals/node_modules/mongodb/lib/mongodb/connection/connection.js:321:22)
18:07:46 worker.1 |    at Socket.EventEmitter.emit (events.js:95:17)
18:07:46 worker.1 |    at Socket.<anonymous> (_stream_readable.js:746:14)
18:07:46 worker.1 |    at Socket.EventEmitter.emit (events.js:92:17)
18:07:46 worker.1 |    at emitReadable_ (_stream_readable.js:408:10)
18:07:46 worker.1 |    at emitReadable (_stream_readable.js:404:5)
18:07:46 worker.1 |    at readableAddChunk (_stream_readable.js:165:9)
18:07:46 worker.1 |    at Socket.Readable.push (_stream_readable.js:127:10)
18:07:46 worker.1 |    at TCP.onread (net.js:526:21)
[DONE] Killing all processes with signal  null
18:07:46 worker.1 Exited Abnormally

**Comment by andreareginato** [comment] 2016-02-28 18:13
Hi @boonpin1975. I've bee trying it out locally without being able to reproduce the bug. The only thing that could be different is the Job table not being a capped collection. To eventually fix this bug I added the explicit definition of the capped collection in lelylan/physicals. 

https://github.com/lelylan/physicals/commit/bdb5c18901573d092d47d7a6cd0e15b30930ed5c

Pull the latest versione in master and let me know how it goes.
Thanks a lot for your time.

**Comment by boonpin1975** [comment] 2016-03-02 02:55
I put the last version , when run nf start , the same error still exists ... my ubuntu is 14.04 64 bits  ,thanks

**Comment by boonpin1975** [comment] 2016-03-02 03:03
I upload the the strace file  
[strace.txt](https://github.com/lelylan/lelylan/files/154029/strace.txt)

**Comment by andreareginato** [comment] 2016-03-03 08:20
Hi @boonpin1975, can you tell me the node version you are using? We made our tests with a pretty old version (0.10.x) and that may be one of the possible reasons. Let us know, so that I can further investigate.

**Comment by boonpin1975** [comment] 2016-03-03 08:24
hi @andreareginato 
  I install the node from ubuntu apt-get version 0.10.25 , thanks !

**Comment by andreareginato** [comment] 2016-04-22 08:43
Hi @boonpin1975, unluckily we were not able to reproduce the problem you are encountering. Did you have any chance on solving the problem?

**Comment by andreareginato** [comment] 2017-03-19 18:39
Closing this issue. 

There is a whole refactoring to make Lelylan work with Docker thanks to @FedeG.
Feel free to reopen the issue if you feel to.

**Closed** 2017-03-19 19:09 UTC
